version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '04:00'
    # Open Dependabot PRs against the deps-updates branch,
    # so grouped updates can be tested there before merging into main
    target-branch: 'deps-updates'
    open-pull-requests-limit: 10
    groups:
      # Group Mantine UI updates together to ensure consistency
      mantine:
        patterns:
          - '@mantine/*'
          - 'postcss-preset-mantine'
      # Group React updates together to ensure compatibility
      # between react and react-dom
      react:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react'
      # Group Electron related packages
      electron:
        patterns:
          - 'electron'
          - 'electron-*'
      next:
        patterns:
          - 'next'
          - '@next/*'
          - 'next-*'
      dexie:
        patterns:
          - 'dexie'
          - 'dexie-*'
